/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVehicleRouteImport } from './routes/api/vehicle'
import { Route as ApiTokenRouteImport } from './routes/api/token'
import { Route as ApiAdminSplatRouteImport } from './routes/api/admin.$'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVehicleRoute = ApiVehicleRouteImport.update({
  id: '/api/vehicle',
  path: '/api/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenRoute = ApiTokenRouteImport.update({
  id: '/api/token',
  path: '/api/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/token': typeof ApiTokenRoute
  '/api/vehicle': typeof ApiVehicleRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/token': typeof ApiTokenRoute
  '/api/vehicle': typeof ApiVehicleRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/token': typeof ApiTokenRoute
  '/api/vehicle': typeof ApiVehicleRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/api/token' | '/api/vehicle' | '/api/admin/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/api/token' | '/api/vehicle' | '/api/admin/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/token'
    | '/api/vehicle'
    | '/api/admin/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiTokenRoute: typeof ApiTokenRoute
  ApiVehicleRoute: typeof ApiVehicleRoute
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicle': {
      id: '/api/vehicle'
      path: '/api/vehicle'
      fullPath: '/api/vehicle'
      preLoaderRoute: typeof ApiVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token': {
      id: '/api/token'
      path: '/api/token'
      fullPath: '/api/token'
      preLoaderRoute: typeof ApiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiTokenRoute: ApiTokenRoute,
  ApiVehicleRoute: ApiVehicleRoute,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
